HolidayCountdownMVC/Models/ErrorViewModel.cs
using System;

namespace HolidayCountdownMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

HolidayCountdownMVC/Models/Gift.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HolidayCountdownMVC.Models
{
    public class Gift
    {
        [Key]
        public int GiftId { get; set; }

        [Column(TypeName = "nvarchar(250)")]
        [Required]
        public string Item { get; set; }

        [Column(TypeName = "nvarchar(250)")]
        [Required]
        public string Recipient { get; set; }

        [Column(TypeName = "decimal(18, 2)")]
        [Required]
        public decimal Price { get; set; }
    }
}

HolidayCountdownMVC/Models/GiftContext.cs
using System;
using Microsoft.EntityFrameworkCore;

namespace HolidayCountdownMVC.Models
{
    public class GiftContext:DbContext
    {
        public GiftContext(DbContextOptions<GiftContext> options):base(options)
        {

        }

        public DbSet<Gift> Gifts { get; set; }
    }
}

HolidayCountdownMVC/Controllers/GiftController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HolidayCountdownMVC.Models;

namespace HolidayCountdownMVC.Controllers
{
    public class GiftController : Controller
    {
        private readonly GiftContext _context;

        public GiftController(GiftContext context)
        {
            _context = context;
        }

        // GET: Gift
        public async Task<IActionResult> Index()
        {
            return View(await _context.Gifts.ToListAsync());
        }

        // GET: Gift/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gift = await _context.Gifts
                .FirstOrDefaultAsync(m => m.GiftId == id);
            if (gift == null)
            {
                return NotFound();
            }

            return View(gift);
        }

        // GET: Gift/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Gift/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("GiftId,Item,Recipient,Price")] Gift gift)
        {
            if (ModelState.IsValid)
            {
                _context.Add(gift);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(gift);
        }

        // GET: Gift/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gift = await _context.Gifts.FindAsync(id);
            if (gift == null)
            {
                return NotFound();
            }
            return View(gift);
        }

        // POST: Gift/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("GiftId,Item,Recipient,Price")] Gift gift)
        {
            if (id != gift.GiftId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(gift);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GiftExists(gift.GiftId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(gift);
        }

        // GET: Gift/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gift = await _context.Gifts
                .FirstOrDefaultAsync(m => m.GiftId == id);
            if (gift == null)
            {
                return NotFound();
            }

            return View(gift);
        }

        // POST: Gift/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var gift = await _context.Gifts.FindAsync(id);
            _context.Gifts.Remove(gift);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GiftExists(int id)
        {
            return _context.Gifts.Any(e => e.GiftId == id);
        }
    }
}

HolidayCountdownMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using HolidayCountdownMVC.Models;

namespace HolidayCountdownMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

HolidayCountdownMVC/Views/Gift/Create.cshtml
@model HolidayCountdownMVC.Models.Gift

@{
    ViewData["Title"] = "Create";
}

<h4>Create Gift</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Item" class="control-label"></label>
                <input asp-for="Item" class="form-control" />
                <span asp-validation-for="Item" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Recipient" class="control-label"></label>
                <input asp-for="Recipient" class="form-control" />
                <span asp-validation-for="Recipient" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HolidayCountdownMVC/Views/Gift/Delete.cshtml
@model HolidayCountdownMVC.Models.Gift

@{
    ViewData["Title"] = "Delete";
}

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Gift</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Item)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Item)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Recipient)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Recipient)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="GiftId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

HolidayCountdownMVC/Views/Gift/Details.cshtml
@model HolidayCountdownMVC.Models.Gift

@{
    ViewData["Details"] = "Details";
}

<div>
    <h4>Gift</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Item)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Item)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Recipient)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Recipient)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.GiftId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

HolidayCountdownMVC/Views/Gift/Edit.cshtml
@model HolidayCountdownMVC.Models.Gift

@{
    ViewData["Title"] = "Edit";
}

<h4>Edit Gift</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="GiftId" />
            <div class="form-group">
                <label asp-for="Item" class="control-label"></label>
                <input asp-for="Item" class="form-control" />
                <span asp-validation-for="Item" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Recipient" class="control-label"></label>
                <input asp-for="Recipient" class="form-control" />
                <span asp-validation-for="Recipient" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

HolidayCountdownMVC/Views/Gift/Index.cshtml
@model IEnumerable<HolidayCountdownMVC.Models.Gift>

@{
    ViewData["Title"] = "Index";
}

<h4>Gift List</h4>

<table class="table table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Item)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Recipient)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                <a asp-action="Create" class="btn btn-outline-success"><i class="fa fa-plus-square"></i>Create New Gift</a>
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Item)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Recipient)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.GiftId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.GiftId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.GiftId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>


HolidayCountdownMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

HolidayCountdownMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Holiday Countdown MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Holiday Countdown MVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Gift" asp-action="Index">Gift</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - <a href="https://twitter.com/carltonstith">&#64;carltonstith</a> CeeJayS Media - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>